/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test_Oriente_Objet;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author salaheddine
 */
public class List extends javax.swing.JPanel {

    public JLabel[] ourLabels = new JLabel[]{
           
           new JLabel("Nom"),
           new JLabel("Taille"),
           new JLabel("Chemin"),
           new JLabel("Date"),
           new JLabel("Type")
           
           };
    
JScrollPane scrollPane;
    Box box;
   
    public void setSize() {
        for(int i=0;i<5;i++)ourLabels[i].setSize(130, 30);
    }
    //JPanel jPanel3 = new JPanel(); 
    //JScrollPane jScrollPane1 = new JScrollPane();
    String rt[]={"a","b","c","d","e","1","2","3","4","5","A","B","C","D","E"};
    
    public List() {
        setSize();
        initComponents();
        scrollPane = new JScrollPane();
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.getVerticalScrollBar().setUnitIncrement(15);
        box = Box.createVerticalBox();
        scrollPane.getViewport().add(box);
        //jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));
        List1(rt);
        //jScrollPane1.setViewportView(jPanel3);
        //add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 220));
        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 220));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ent(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jLabel4.setText("Taille");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 120, 30));

        jLabel5.setText("Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, 30));

        jLabel2.setText("Type");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 100, 30));

        jLabel1.setText("Chemin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 190, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));
    }// </editor-fold>//GEN-END:initComponents
int x=0;
    private void ent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ent
       if(x%2==0)jPanel1.setBackground(Color.red);
        if(x%2==1)jPanel1.setBackground(Color.blue);
        x++;
    }//GEN-LAST:event_ent

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseExited

   public void List1(String str[]) {
         
        int i=0;int n=-1;
        JPanel jPanel = new JPanel();
        //for(int p=0;p<str.length/5;p++)
            jPanel.setLayout(new BoxLayout(jPanel, BoxLayout.X_AXIS));
            
        
        while(i<str.length){
            if(i%5==0)n++;
                       
                        
                        
                        
                        if(i<5)
                        {   
                            ourLabels[i].setText(str[i]);
                            jPanel.add(ourLabels[i]);
                        }
                        else if(i%5==0 && i>4)
                        {   System.out.println(str[i]);
                            ourLabels[0].setText(str[i]);
                            jPanel.add(ourLabels[0]);
                        }
                        else if(i%5==1 && i>5)
                        {   System.out.println(str[i]);
                            ourLabels[1].setText(str[i]);
                            jPanel.add(ourLabels[1]);
                        }
                        else if(i%5==2 && i>5)
                        {   System.out.println(str[i]);
                            ourLabels[2].setText(str[i]);
                           jPanel.add(ourLabels[2]);
                        }
                        else if(i%5==3 && i>5)
                        {   System.out.println(str[i]);
                            ourLabels[3].setText(str[i]);
                            jPanel.add(ourLabels[3]);
                        }
                        else if(i%5==4 && i>5)
                        {   System.out.println(str[i]);
                            ourLabels[4].setText(str[i]);
                            jPanel.add(ourLabels[4]);
                        }
                        else System.out.println("Errors");

                    jPanel.revalidate();
                    jPanel.setVisible(true);
                    box.add(jPanel, 0);
                scrollPane.validate();
                    i++;
        }
        
   }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

public static void main(String arg[]){
    
        JFrame Frame = new JFrame();
        List lis = new List();
        Frame.setSize(900, 500);
        Frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Frame.add(lis);
        Frame.setVisible(true);
    
    }

}

