/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package_Search;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;


/**
 *
 * @author salaheddine
 */
public class StartGUI extends javax.swing.JFrame {

    int countsearch;
    int countmenu;
    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Package_Search/Disign/iconofihelp.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Close_button = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Lope_icon = new javax.swing.JLabel();
        Text_search = new javax.swing.JTextField();
        Search1_icon = new javax.swing.JLabel();
        Login_icon = new javax.swing.JLabel();
        Signup_icon = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        Backgroud2 = new javax.swing.JLabel();
        Backgound1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package_Search/Disign/icon_close.png"))); // NOI18N
        Close_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(Close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package_Search/Disign/applogo.png"))); // NOI18N
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 110));

        Lope_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package_Search/Disign/loupe.png"))); // NOI18N
        Lope_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lope_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lope_iconMouseClicked(evt);
            }
        });
        getContentPane().add(Lope_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 120, 120));

        Text_search.setBorder(null);
        Text_search.setEnabled(false);
        Text_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_searchMouseClicked(evt);
            }
        });
        Text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_searchActionPerformed(evt);
            }
        });
        Text_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text_searchKeyPressed(evt);
            }
        });
        getContentPane().add(Text_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 75, 220, 30));

        Search1_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package_Search/Disign/search0.png"))); // NOI18N
        getContentPane().add(Search1_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 260, 60));

        Login_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package_Search/Disign/login-button.png"))); // NOI18N
        Login_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Login_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 130, 40));

        Signup_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package_Search/Disign/signup-button.png"))); // NOI18N
        Signup_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Signup_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 110, 40));

        help.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 147, 160, 20));
        getContentPane().add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, 20));
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 190));

        Backgroud2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package_Search/Disign/barVide.png"))); // NOI18N
        Backgroud2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Backgroud2MouseClicked(evt);
            }
        });
        getContentPane().add(Backgroud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        Backgound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package_Search/Disign/blue minimalistic.jpg"))); // NOI18N
        getContentPane().add(Backgound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Close_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_buttonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Close_buttonMouseClicked

    private void Text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_searchActionPerformed

    public static String GetText_search()
    {
        return Text_search.getText();
    }
    
    private void Text_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_searchMouseClicked

        if(countsearch == 0)
        {
            Text_search.setEnabled(true);
            Text_search.setEditable(true);
            Text_search.setText("Search");
            ImageIcon II = new ImageIcon(getClass().getResource("/Package_Search/Disign/search1.png"));
            Search1_icon.setIcon(II);
            //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChercherUnFichier/bg/search1.png")));
            countsearch = 1;
        }
    }//GEN-LAST:event_Text_searchMouseClicked

    private void Backgroud2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Backgroud2MouseClicked
        if(countsearch == 1)
        {
            
            Text_search.setEditable(true);
            Text_search.setText("");
            ImageIcon II = new ImageIcon(getClass().getResource("/Package_Search/Disign/search0.png"));
            Search1_icon.setIcon(II);
            //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChercherUnFichier/bg/search1.png")));
            countsearch = 0;
        }
        
    }//GEN-LAST:event_Backgroud2MouseClicked

    private void Lope_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lope_iconMouseClicked
        //code a traiter
    }//GEN-LAST:event_Lope_iconMouseClicked

    private void Text_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_searchKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {  
                //CODE A TRAITER
               
            }
    }//GEN-LAST:event_Text_searchKeyPressed

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked

        
        if(countmenu == 0)
        {
        ImageIcon II = new ImageIcon(getClass().getResource("/Package_Search/Disign/menu.png"));
            Menu.setIcon(II); 
            help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            countmenu = 1;
        }
        else 
        {
        if(countmenu == 1)
        {
        ImageIcon II = new ImageIcon(getClass().getResource(""));
            Menu.setIcon(II); 
            help.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            about.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            countmenu = 0;
        }
        
        }
        
    }//GEN-LAST:event_LogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try{
                    Thread.sleep(10);
                   }
                
                catch (Exception e){  }
                
                
                
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgound1;
    private javax.swing.JLabel Backgroud2;
    private javax.swing.JLabel Close_button;
    private javax.swing.JLabel Login_icon;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Lope_icon;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Search1_icon;
    private javax.swing.JLabel Signup_icon;
    private static javax.swing.JTextField Text_search;
    private javax.swing.JLabel about;
    private javax.swing.JLabel help;
    // End of variables declaration//GEN-END:variables
}
