/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPanels;

import Package_Search.DisplayTrayIcon;
import java.awt.TrayIcon;

/**
 *
 * @author salaheddine
 */
public class Menu_Rechercher extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Rechercher
     */
    public Menu_Rechercher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scan_group = new javax.swing.ButtonGroup();
        taille_group = new javax.swing.ButtonGroup();
        scan_auto_group = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        MenuPanal2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboType_File = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel_file_type = new javax.swing.JPanel();
        jLabel_type_file = new javax.swing.JLabel();
        jTextField_type_file = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Scane_text = new javax.swing.JLabel();
        Scan_path = new javax.swing.JTextField();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        scan_label = new javax.swing.JLabel();
        scan_label1 = new javax.swing.JLabel();
        jToggleButton_on = new javax.swing.JToggleButton();
        jToggleButton_off = new javax.swing.JToggleButton();
        Scan_automatique_Panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Scan_au_démarrage_CheckBox = new javax.swing.JCheckBox();
        Time_Type_ComboBox = new javax.swing.JComboBox();
        Time_jSpinner = new javax.swing.JSpinner();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel1.setText("Type :");

        jLabel6.setText("Date :");

        jLabel7.setText("Taille :");

        jLabel8.setText("Lange :");

        jLabel9.setText("Genre :");

        jLabel10.setText("Auteur :");

        ComboType_File.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "PDF", "xlsx", "docx", "txt", "java", "c", "c++", "Autre" }));
        ComboType_File.setToolTipText("");
        ComboType_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboType_FileActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "1 jour", "2 jours", "5 jours", "1 semaine", "1 mois", "other" }));

        taille_group.add(jRadioButton1);
        jRadioButton1.setText("0 Kb --> 10 Kb");

        taille_group.add(jRadioButton2);
        jRadioButton2.setText("10 Kb --> 1 Mb");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        taille_group.add(jRadioButton3);
        jRadioButton3.setText("1 Mb --> 10 Mb");

        taille_group.add(jRadioButton4);
        jRadioButton4.setText("10 Mb --> ...");

        taille_group.add(jRadioButton5);
        jRadioButton5.setText("Unknown");

        jPanel_file_type.setOpaque(false);
        jPanel_file_type.setVisible(false);

        jLabel_type_file.setText("Votre Type :");

        javax.swing.GroupLayout jPanel_file_typeLayout = new javax.swing.GroupLayout(jPanel_file_type);
        jPanel_file_type.setLayout(jPanel_file_typeLayout);
        jPanel_file_typeLayout.setHorizontalGroup(
            jPanel_file_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_file_typeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_type_file)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_type_file, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_file_typeLayout.setVerticalGroup(
            jPanel_file_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_file_typeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_file_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_type_file)
                    .addComponent(jTextField_type_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuPanal2Layout = new javax.swing.GroupLayout(MenuPanal2);
        MenuPanal2.setLayout(MenuPanal2Layout);
        MenuPanal2Layout.setHorizontalGroup(
            MenuPanal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MenuPanal2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(MenuPanal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanal2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel_file_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MenuPanal2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanal2Layout.createSequentialGroup()
                        .addGroup(MenuPanal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuPanal2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(ComboType_File, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuPanal2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MenuPanal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1))))
                        .addContainerGap(64, Short.MAX_VALUE))))
        );
        MenuPanal2Layout.setVerticalGroup(
            MenuPanal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanal2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MenuPanal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboType_File, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_file_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(MenuPanal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MenuPanal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanal2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanal2Layout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(73, 73, 73))
        );

        jTabbedPane1.addTab("Recherche Avancer", MenuPanal2);

        jPanel1.setEnabled(false);

        jButton1.setText("Scan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Scane_text.setText("Lancer la rechercher à partir de :");

        Scan_path.setText("/Users/salaheddine/Desktop/");

        scan_group.add(jRadioButton6);
        jRadioButton6.setText("Racine");

        scan_group.add(jRadioButton7);
        jRadioButton7.setSelected(true);
        jRadioButton7.setText("Autre chemin [...]");

        scan_label.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        scan_label.setForeground(new java.awt.Color(0, 144, 82));
        scan_label.setText("Scan manuel :");

        scan_label1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        scan_label1.setForeground(new java.awt.Color(0, 144, 82));
        scan_label1.setText("Scan automatique :");

        scan_auto_group.add(jToggleButton_on);
        jToggleButton_on.setSelected(true);
        jToggleButton_on.setText("ON");
        jToggleButton_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_onActionPerformed(evt);
            }
        });

        scan_auto_group.add(jToggleButton_off);
        jToggleButton_off.setText("OFF");
        jToggleButton_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_offActionPerformed(evt);
            }
        });

        Scan_automatique_Panel.setOpaque(false);

        jLabel11.setText("Lancer le scan chaque :");

        Scan_au_démarrage_CheckBox.setSelected(true);
        Scan_au_démarrage_CheckBox.setText("Scan au démarrage");

        Time_Type_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Secondes", "minutes", "Heures", "Jours", "Mois" }));

        Time_jSpinner.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)60), Byte.valueOf((byte)1), Byte.valueOf((byte)60), Byte.valueOf((byte)1)));

        javax.swing.GroupLayout Scan_automatique_PanelLayout = new javax.swing.GroupLayout(Scan_automatique_Panel);
        Scan_automatique_Panel.setLayout(Scan_automatique_PanelLayout);
        Scan_automatique_PanelLayout.setHorizontalGroup(
            Scan_automatique_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Scan_automatique_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Scan_automatique_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Scan_automatique_PanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Scan_au_démarrage_CheckBox))
                    .addComponent(jLabel11)
                    .addGroup(Scan_automatique_PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Time_jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Time_Type_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Scan_automatique_PanelLayout.setVerticalGroup(
            Scan_automatique_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Scan_automatique_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Scan_au_démarrage_CheckBox)
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addGroup(Scan_automatique_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Time_jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Scan_automatique_PanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Time_Type_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(scan_label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Scane_text))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButton7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jToggleButton_on, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scan_label1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jToggleButton_off, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Scan_automatique_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Scan_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(scan_label)
                .addGap(23, 23, 23)
                .addComponent(Scane_text)
                .addGap(12, 12, 12)
                .addComponent(jRadioButton6)
                .addGap(6, 6, 6)
                .addComponent(jRadioButton7)
                .addGap(6, 6, 6)
                .addComponent(Scan_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton_on)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(scan_label1))
                    .addComponent(jToggleButton_off))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Scan_automatique_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Scane", jPanel1);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ComboType_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboType_FileActionPerformed
        File_type();
    }//GEN-LAST:event_ComboType_FileActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DisplayTrayIcon.trayIcon.displayMessage("Scan erroné", "Le Scan n'est pas déclencher", TrayIcon.MessageType.WARNING);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_onActionPerformed
        scan_automatique_show();
    }//GEN-LAST:event_jToggleButton_onActionPerformed

    private void jToggleButton_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_offActionPerformed
        scan_automatique_show();
    }//GEN-LAST:event_jToggleButton_offActionPerformed
                                            
    
    public void scan_automatique_show(){
        if(jToggleButton_off.isSelected()){
            Scan_automatique_Panel.setVisible(false);
            //il faut stocker le resultat de test pour le prochaine démarage dans une B.D
        }
        else if(jToggleButton_on.isSelected()){
            Scan_automatique_Panel.setVisible(true);
        }
    }
    
    public void File_type(){
        
        if(ComboType_File.getSelectedIndex()!=8){
            jPanel_file_type.setVisible(false);
        }
        else{
            jPanel_file_type.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboType_File;
    private javax.swing.JPanel MenuPanal2;
    private javax.swing.JCheckBox Scan_au_démarrage_CheckBox;
    public javax.swing.JPanel Scan_automatique_Panel;
    private javax.swing.JTextField Scan_path;
    private javax.swing.JLabel Scane_text;
    private javax.swing.JComboBox Time_Type_ComboBox;
    private javax.swing.JSpinner Time_jSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_type_file;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_file_type;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_type_file;
    private javax.swing.JToggleButton jToggleButton_off;
    private javax.swing.JToggleButton jToggleButton_on;
    private javax.swing.ButtonGroup scan_auto_group;
    private javax.swing.ButtonGroup scan_group;
    private javax.swing.JLabel scan_label;
    private javax.swing.JLabel scan_label1;
    private javax.swing.ButtonGroup taille_group;
    // End of variables declaration//GEN-END:variables
}
